name: 'Review Agent'
description: 'Summarize, review and suggest improvements for pull requests'
branding:
  icon: 'award'
  color: 'green'
runs:
  using: 'docker'
  #image: 'docker://tamtom/ai-pr-agent:github_action'
  image: 'Dockerfile'
