# Base stage
FROM python:3.10 as base
RUN mkdir -p /app
WORKDIR /app
ADD pyproject.toml .
ADD requirements.txt .
RUN pip install . && rm pyproject.toml requirements.txt
ENV PYTHONPATH=/app
ADD ai_pr_agent ai_pr_agent
ADD github_action/entrypoint.sh /
RUN chmod +x /entrypoint.sh
RUN echo "entrypoint.sh..."
ENTRYPOINT ["entrypoint.sh"]
