# Base stage
FROM python:3.10 as base

WORKDIR /app
COPY pyproject.toml requirements.txt ./
RUN echo "Installing dependencies..." && \
    pip install . && \
    echo "Cleaning up pyproject.toml and requirements.txt..." && \
    rm pyproject.toml requirements.txt
ENV PYTHONPATH=/app

# GitHub Action stage
FROM base
WORKDIR /app
COPY ai_pr_agent ai_pr_agent
COPY github_action/entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]
